* Why take notes

** Introduction

I've been fond of notetaking for approximately the last 4 years. Notetaking systems I've used
extensively are:

- [[https://workflowy.com][Workflowy]]. You'll probably notice that I love hierarchical lists.
- [[https://apps.ankiweb.net][Anki]]. Yes, I used it not only for spaced repetition, but also as a poor man's knowledge base.
- Paper notebooks. One notebook per mathematical subject.
- [[https://orgmode.org/][Emacs org-mode]]

Right now I am trying the latest rationalist fad - [[https://www.greaterwrong.com/posts/NfdHG6oHBJ8Qxc26s/the-zettelkasten-method-1][Zettelkasten using paper]]. I like it, but it's far from ideal, so
yesterday I've been thinking about what else I could try and how I should choose a notetaking
system. This document is me writing down those thoughts as a blog post.

** What I get or hope to get from notetaking

Here goes my list of ways how notetaking can improve my life. Each item has importance assigned
from /low/ to /very high/.

- It facilitates thinking useful thoughts. This has two components.
  + For me it's nigh impossible to think a long and complicated thought without an extension of
    my working memory in the form of paper, whiteboard, or a computer with a text editor. For
    some magical reason ("habits" and absence distractions are my best hypotheses)
    this works much better for me with
    paper than with a computer. My best hypotheses for why this is the case are: due to habits
    I am used to thinking on paper and not getting distracted, and due to other habits I get
    distracted all the time when using computer or phone; writing on paper is slower than
    typing, so this forces my mind to slow down.
    If I need to think about something complicated, I put a sheet
    of paper on the table, take a pencil and start writing my thoughts. Notice that it's not
    necessary to even keep notes for this effect to work. Although knowing that the note will
    go into my knowledge base gives me motivation to write it. /importance: very high/
  + Finding useful connections between notes by linking. This is what zettelkasten is all
    about. I am actually not sure if this is important. But it might be, and right now I want
    to try Zettelkasten for real, so I am rating it as /importance: high/
- Knowledge base. I.e. having quick access in the future to knowledge I write down today in a
  form which will be easy for me to understand. For example, yesterday I forgot how integration
  by parts works. I went to the [[https://en.wikipedia.org/wiki/Integration_by_parts][wikipedia]] but ∫u dv = uv - ∫v du is not how I've
  learned it. So I looked it up in my anki and found (f ⋅ g)' = f' ⋅ g + f ⋅ g',
  which is much more intuitive for me. So, my notes, by the virtue of being mine, are tailor
  made for me. /importance: high/
- It improves my memorization. /importance: medium/
  + There is a bunch of research showing that writing things down when studying improved
    memorization. Most of that research focuses on writing things by hand. I don't buy
    into the premise that precise muscle movements which happen when writing by hand
    is the important thing here, I think it's mainly the act of thinking about the thing that
    much more thoroughly, maybe with something else. So I don't think handwriting is much
    better at this than writing on the computer.
  + Hopefully a good knowledge base will show me useful notes I made in the past, and this
    will work as kinda [[http://www.gwern.net/Spaced%20repetition][spaced repetition]].
- Being able to free up my working memory because I know I won't forget about important
  things - my notetaking system will remind me of them. This is one of the important
  considerations behind David Allen's "Getting things done" method. I think this is useful not
  only for remembering to do my todos. Also, if I know I've written down this very important
  thought I am having in my notetaking system where it probably won't get lost and completely
  forgotten, I can go to sleep now rather than frantically trying to finish thinking about it
  now. The part about being able to go to sleep seems extremely plausible, while the part about
  freeing up the working memory seems somewhat plausible (25% probability
  of actually working like that, since
  by default I consider all psychological theories to be false). I haven't specifically seeked
  research about the working memory component. Would be glad if someone sent my a summarization
  or a meta analysis. /importance: medium/
- It facilitates writing blog posts. Having a blog is useful for signaling
  intelligence and other good things. In this regard, computer based notetaking systems win,
  because copy pasting text is much easier than typing it while looking at my paper notes.
  /importance: medium/
- A notetaking system can also be a todo system. Todo systems allow me not to forget important
  things which I need to do. But it's trivial to use google calendar or something like that for
  todos instead, so I am marking this as /importance: low/

** Desiderata for a notetaking system

Here I list characteristics I want a notetaking system to have. They are useful to
compare different notetaking systems. They aren't all absolutely critical.

- Given a topic, it should be easy to look up notes about it.
- Quick adding new notes and editing existing notes
- Low cognitive burden of using the system. After getting used to it, at least.
- Future-proof. It should be easy to switch from this system to another one and keep the
  notes. The system shouldn't suddenly stop working (for example because the creator
  went bankrupt). The system should work on different platforms I might use in the future
  (e.g. on Windows computers with restricted software installation if my future employer forces
  me to use one).
- I should be able to take the system with me. So, having an Android program would be nice.
- I should be able to use it comfortably not only behind my table (for example if it's
  difficult to use the notetaking program on small laptop screen), but just about
  anywhere. This characteristic is probably not important for many people, but for me sitting all day long
  behind a table causes back pain.
- Using the system should feel nice.
- It should be easy to put brain dump notes in the system if I decide that I want them there.
- If it's software, it should be customizable.
- If it's software, it should be unable or unlikely to access my system, other files, etc. and
  use them in ways which are bad for me.
- Other people shouldn't be able or should be unlikely to read my notes stored in the system.

** Notetaking systems I might want to try and what characteristics they have

*** The table

Here I list some notetaking systems I want to try (or have already tried but want to give them
another chance) as rows of a table. Columns are desiderata. The desiderata are mentioned in the previous section but they
don't map one to one and not all of those desiderata are present as columns here. I rate each
desideratum from + (high importance) to 0 (medium importance) to - (low importance). Each cell contains a rating of how
well the notetaking system satisfies the desideratum from -- to 0 to ++ or it contains a range like
[-, ++] if I am not sure and I think it can be anywhere from - (inclusive) to ++ (inclusive).


| System             | Facilitates thoughts by magic 1 | Facilitates thoughts by linking 0 | Quick lookup 0 | Quick adding 1 | Quick editing 0 | Transferable 0 | Will work 0 | Forces same pose 1 | Can use everywhere always 0 | Facilitates writing for public -1 |
|--------------------+---------------------------------+-----------------------------------+----------------+----------------+-----------------+----------------+-------------+--------------------+-----------------------------+-----------------------------------|
| Paper zettelkasten |                                 |                                   |                |                |                 |                |             |                    |                             |                                   |
| Roam               |                                 |                                   |                |                |                 |                |             |                    |                             |                                   |
| [[https://github.com/jethrokuan/org-roam][org-roam]]           |                                 |                                   |                |                |                 |                |             |                    |                             |                                   |
|                    |                                 |                                   |                |                |                 |                |             |                    |                             |                                   |

*** Why these systems have these ratings
- Transferable :: it means how easy and quickly you can transfer your notes from this system to
  anothre system you might want to use. Easiest with markdown, slightly more difficult with
  org-mode, much more difficult with paper or proprietary systems.
- Will work :: this is something like expected time during which the system will continue
  working, i.e. if it's a web service, it won't close, if it's a desktop program which needs
  maintenance, it will continue to be maintained, and if it's a paper system, it won't get
  stolen or burned.
- Forces same pose :: this is once again about me getting back pain from sitting behind a
  table.
  + Org-roam's sidebar for showing backlinks sucks, so without a lot of tinkering I can only
    use it comfortably on a big screen, which forces me to sit at my desk rather than move
    around my home with my laptop.
- Can use everywhere always :: whether I can take the system with me everywhere I go.
  + Paper notebook is easy to take on a walk but I won't be able to take all my notebooks when
    I have many.
  + org-roam will never have a mobile app.
  + Roam requires internet access but might get a mobile app.
